//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumenMedico.Consultorio
{


	public partial class Recepcion
	{

		/// <summary>
		/// ramMan control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadAjaxManager ramMan;

		/// <summary>
		/// ralpImage control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadAjaxLoadingPanel ralpImage;

		/// <summary>
		/// vsErrors control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.ValidationSummary vsErrors;

		/// <summary>
		/// hfRutImg control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HiddenField hfRutImg;

		/// <summary>
		/// rbtnValidate control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadButton rbtnValidate;

		/// <summary>
		/// hdIdPaciente control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HiddenField hdIdPaciente;

		/// <summary>
		/// rauFoto control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadAsyncUpload rauFoto;

		/// <summary>
		/// hfIdHistoria control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HiddenField hfIdHistoria;

		/// <summary>
		/// ruTestFoto control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadUpload ruTestFoto;

		/// <summary>
		/// rtxtGeneroValue control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox rtxtGeneroValue;

		/// <summary>
		/// rtxtFechaNacCompare control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox rtxtFechaNacCompare;

		/// <summary>
		/// imgPrePhoto control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadBinaryImage imgPrePhoto;

		/// <summary>
		/// rbtnCargarImagen control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadButton rbtnCargarImagen;

		/// <summary>
		/// rcbxTipoDoc control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadComboBox rcbxTipoDoc;

		/// <summary>
		/// rfvTipDoc control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTipDoc;

		/// <summary>
		/// rtxtNumDoc control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox rtxtNumDoc;

		/// <summary>
		/// rfvNumDoc control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNumDoc;

		/// <summary>
		/// rtxtPasaporte control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox rtxtPasaporte;

		/// <summary>
		/// rtxtNombres control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox rtxtNombres;

		/// <summary>
		/// rfvNombres control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNombres;

		/// <summary>
		/// rtxtApellidos control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox rtxtApellidos;

		/// <summary>
		/// rfvApellidos control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvApellidos;

		/// <summary>
		/// rblGenero control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RadioButtonList rblGenero;

		/// <summary>
		/// rdpFecNac control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadDatePicker rdpFecNac;

		/// <summary>
		/// rfvFecNac control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFecNac;

		/// <summary>
		/// cvFecNac control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.CompareValidator cvFecNac;

		/// <summary>
		/// rcbxEmbajada control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadComboBox rcbxEmbajada;

		/// <summary>
		/// rcbxTipoVisa control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadComboBox rcbxTipoVisa;

		/// <summary>
		/// rtxtNumVisa control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox rtxtNumVisa;

		/// <summary>
		/// chkPrioritario control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.CheckBox chkPrioritario;

		/// <summary>
		/// chkPacienteExterno control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.CheckBox chkPacienteExterno;

		/// <summary>
		/// chkRequiereNot control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.CheckBox chkRequiereNot;

		/// <summary>
		/// chkNotEnv control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.CheckBox chkNotEnv;

		/// <summary>
		/// rtxtDireccion control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox rtxtDireccion;

		/// <summary>
		/// rtxtTelefono control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox rtxtTelefono;

		/// <summary>
		/// rtxtCorreo control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox rtxtCorreo;

		/// <summary>
		/// revCorreo control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.RegularExpressionValidator revCorreo;

		/// <summary>
		/// rtxtAcudiente control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox rtxtAcudiente;

		/// <summary>
		/// chckbxMed control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.CheckBox chckbxMed;

		/// <summary>
		/// chckbxRad control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.CheckBox chckbxRad;

		/// <summary>
		/// chckbxLab control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.CheckBox chckbxLab;

		/// <summary>
		/// rlbExamenes control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadListBox rlbExamenes;

		/// <summary>
		/// listaAnexos control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadAjaxPanel listaAnexos;

		/// <summary>
		/// rbtnRefreshAnnex control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadButton rbtnRefreshAnnex;

		/// <summary>
		/// rtxtComment control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadTextBox rtxtComment;

		/// <summary>
		/// rbtnGuardar control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadButton rbtnGuardar;

		/// <summary>
		/// rbtnFirmar control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadButton rbtnFirmar;

		/// <summary>
		/// rbtnLiberar control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Telerik.Web.UI.RadButton rbtnLiberar;
	}
}
